import { mkdir, writeFile } from "node:fs/promises";
import { loadGameData } from "./rules-loader.mjs";
import { Game } from "./core.mjs";
import { STRATEGIES } from "./bots.mjs";

const count=Math.max(1,Number.parseInt(process.argv[2]??"1000",10)); const output=process.argv[3]??"reports/simulation-v2.3.json"; const data=await loadGameData();
const baseline={...data,definition:structuredClone(data.definition)};baseline.definition.economy.defensePractice.usesPerTurn=0;
const summary={rulesVersion:data.definition.rulesVersion,games:count,generatedAt:new Date().toISOString(),strategies:{},matchups:{},rounds:{sum:0,average:0,min:Infinity,max:0,roundLimitGames:0},turns:{sum:0,average:0},economy:{openingPurchasePlayers:0,openingPurchaseRate:0,turnOneParalysisPlayers:0,withoutDefensePracticeOpeningPurchasePlayers:0,withoutDefensePracticeOpeningPurchaseRate:0,defensePracticeLift:0,averagePurchases:0,totalPurchases:0},cards:{}};
for(let i=0;i<count;i++){const a=STRATEGIES[i%STRATEGIES.length],b=STRATEGIES[Math.floor(i/STRATEGIES.length)%STRATEGIES.length];const result=new Game(data,{seed:i+1,strategies:[a,b]}).run();const baseResult=new Game(baseline,{seed:i+1,strategies:[a,b]}).run();summary.economy.withoutDefensePracticeOpeningPurchasePlayers+=baseResult.players.filter(p=>p.openingPurchase).length;const win=result.players[result.winner].strategy;const key=`${a} vs ${b}`;(summary.matchups[key]??={games:0,wins:{}}).games++;summary.matchups[key].wins[win]=(summary.matchups[key].wins[win]||0)+1;for(const p of result.players){const s=summary.strategies[p.strategy]??={games:0,wins:0,winRate:0};s.games++;if(p.id===result.winner)s.wins++;summary.economy.totalPurchases+=p.purchases;if(p.openingPurchase)summary.economy.openingPurchasePlayers++;else summary.economy.turnOneParalysisPlayers++;}summary.rounds.sum+=result.rounds;summary.rounds.min=Math.min(summary.rounds.min,result.rounds);summary.rounds.max=Math.max(summary.rounds.max,result.rounds);if(result.reason==="round-limit")summary.rounds.roundLimitGames++;summary.turns.sum+=result.turns;for(const c of result.cards){const s=summary.cards[c.id]??={name:c.name,purchased:0,played:0,winnerGames:0};s.purchased+=c.purchased;s.played+=c.played;s.winnerGames+=c.winnerOwned;}}
for(const s of Object.values(summary.strategies))s.winRate=+(s.wins/s.games).toFixed(4);summary.rounds.average=+(summary.rounds.sum/count).toFixed(2);summary.turns.average=+(summary.turns.sum/count).toFixed(2);summary.economy.openingPurchaseRate=+(summary.economy.openingPurchasePlayers/(count*2)).toFixed(4);summary.economy.withoutDefensePracticeOpeningPurchaseRate=+(summary.economy.withoutDefensePracticeOpeningPurchasePlayers/(count*2)).toFixed(4);summary.economy.defensePracticeLift=+(summary.economy.openingPurchaseRate-summary.economy.withoutDefensePracticeOpeningPurchaseRate).toFixed(4);summary.economy.averagePurchases=+(summary.economy.totalPurchases/(count*2)).toFixed(2);for(const c of Object.values(summary.cards)){c.playRate=+(c.played/count).toFixed(4);c.purchaseRate=+(c.purchased/count).toFixed(4);c.winCorrelation=c.purchased?+(c.winnerGames/c.purchased).toFixed(4):0;}
await mkdir(new URL(".",`file://${process.cwd()}/${output}`).pathname,{recursive:true}).catch(()=>{});await writeFile(output,JSON.stringify(summary,null,2)+"\n");const markdown=output.replace(/\.json$/,".md");const strategyRows=Object.entries(summary.strategies).map(([name,s])=>`| ${name} | ${s.games} | ${s.wins} | ${(s.winRate*100).toFixed(1)}% |`).join("\n");await writeFile(markdown,`# Dojo Deckbuilder v2.3 Simulation\n\n${count.toLocaleString()} deterministic Quick Duel bot games.\n\n| Metric | Result |\n|---|---:|\n| Average rounds | ${summary.rounds.average} |\n| Round-limit games | ${summary.rounds.roundLimitGames} |\n| Opening purchase rate | ${(summary.economy.openingPurchaseRate*100).toFixed(1)}% |\n| Without Defense Practice | ${(summary.economy.withoutDefensePracticeOpeningPurchaseRate*100).toFixed(1)}% |\n| Defense Practice lift | ${(summary.economy.defensePracticeLift*100).toFixed(1)} points |\n| Average purchases per player | ${summary.economy.averagePurchases} |\n\n## Strategy results\n\n| Strategy | Seats | Wins | Win rate |\n|---|---:|---:|---:|\n${strategyRows}\n\nThe JSON file contains matchup splits and per-card play, purchase, and winner-association statistics.\n`);console.log(JSON.stringify({games:count,averageRounds:summary.rounds.average,roundLimitGames:summary.rounds.roundLimitGames,openingPurchaseRate:summary.economy.openingPurchaseRate,withoutDefensePractice:summary.economy.withoutDefensePracticeOpeningPurchaseRate,defensePracticeLift:summary.economy.defensePracticeLift,output,markdown},null,2));
