import assert from "node:assert/strict";
import test from "node:test";
import { loadGameData } from "../engine/rules-loader.mjs";
import { Game } from "../engine/core.mjs";

test("engine loads the canonical v2.3 rules and 597 cards",async()=>{const d=await loadGameData();assert.equal(d.definition.rulesVersion,"v2.3");assert.equal(d.cards.length,597);assert.equal(d.definition.economy.defensePractice.usesPerTurn,1);assert.equal(d.definition.economy.market.refill,"top-card-after-purchase");assert.equal(d.definition.economy.market.stagnationRefresh,"after-full-round-without-purchase");});
test("seeded games are deterministic and terminate legally",async()=>{const d=await loadGameData();const a=new Game(d,{seed:42,strategies:["economy","aggression"]}).run();const b=new Game(d,{seed:42,strategies:["economy","aggression"]}).run();assert.deepEqual(a,b);assert.ok(a.winner===0||a.winner===1);assert.ok(a.rounds<=d.definition.mode.maxRounds+1);});
test("Defense Practice grants only printed Focus",async()=>{const d=await loadGameData();const g=new Game(d,{seed:3});const p=g.players[0];const defense=p.hand.find(c=>Number(c.stats?.Guard)>0)??d.byId.get("DDB-STA-CORE-009");if(!p.hand.includes(defense))p.hand.push(defense);const hp=p.hp;assert.equal(g.practice(p,defense),true);assert.equal(p.focus,Number(defense.focusValue));assert.equal(p.hp,hp);});
test("a played Defense grants Focus, is discarded immediately, and cannot block again",async()=>{const d=await loadGameData();const g=new Game(d,{seed:9});const attacker=g.players[0],defender=g.players[1];const attack=d.byId.get("DDB-STA-CORE-003"),secondAttack=d.byId.get("DDB-STA-CORE-004"),defense=d.byId.get("DDB-STA-CORE-009");attacker.hand.push(attack,secondAttack);defender.hand.push(defense);const printed=defense.focus;const before=defender.focus;const first=g.resolveAttack(attacker,defender,attack,{defenseCard:defense});const second=g.resolveAttack(attacker,defender,secondAttack,{defenseCard:null});assert.equal(defender.focus,before+Number(defense.focusValue));assert.equal(defense.focus,printed);assert.equal(first.defense,defense);assert.equal(second.defense,null);assert.ok(defender.discard.includes(defense));assert.ok(!defender.played.includes(defense));});
test("Market purchases preserve remaining Focus and refill exactly one card",async()=>{const d=await loadGameData();const g=new Game(d,{seed:13});const p=g.players[0];const bought=g.market.find(card=>Number.parseInt(String(card.fpCost),10)<=4)??g.market[0];const price=Number.parseInt(String(bought.fpCost),10)||0;p.focus=price+3;const beforeDeck=g.marketDeck.length;assert.equal(g.buy(p,bought),true);assert.equal(p.focus,3);assert.equal(g.market.length,d.definition.economy.market.rowSize);assert.equal(g.marketDeck.length,beforeDeck-1);assert.equal(g.marketPurchasedThisRound,true);assert.ok(p.discard.includes(bought));});
test("a turn may play every legal Attack in hand",async()=>{const d=await loadGameData();const g=new Game(d,{seed:21});const p=g.players[0],defender=g.players[1];p.hand=["DDB-STA-CORE-002","DDB-STA-CORE-003","DDB-STA-CORE-004"].map(id=>d.byId.get(id));p.deck=[];p.discard=[];defender.hp=100;g.botTurn(0);assert.equal(g.events.filter(event=>event.type==="attack"&&event.attacker===0).length,3);});
