import type {
  ComboAttackFact,
  ComboBlockFact,
  ComboPlayedCardFact,
  ComboPurchaseFact,
  ComboRuntimeCard,
  ComboRuntimeContext,
} from "./combo-runtime.ts";

export type ComboHostPlayedFact = { cardId: string; zone?: string };
export type ComboHostAttackFact = { cardId: string; zone?: string; hit: boolean; reversal: boolean; blocked: boolean };
export type ComboHostBlockFact = { defenseCardId?: string; incomingZone?: string; equipmentCount?: number };
export type ComboHostPurchaseFact = { cardId: string };

export type ComboHostFacts = {
  startingHandIds: string[];
  turnPlayed: ComboHostPlayedFact[];
  roundPlayed: ComboHostPlayedFact[];
  sinceLastTurnPlayed: ComboHostPlayedFact[];
  turnAttacks: ComboHostAttackFact[];
  roundAttacks: ComboHostAttackFact[];
  sinceLastTurnAttacks: ComboHostAttackFact[];
  roundBlocks: ComboHostBlockFact[];
  sinceLastTurnBlocks: ComboHostBlockFact[];
  speedGainedSinceLastTurn: boolean;
  purchasesSinceLastAscend: ComboHostPurchaseFact[];
  previousAttackBlocked: boolean;
};

export type ComboHostBaseContext = Omit<
  ComboRuntimeContext,
  | "startingHand"
  | "roundZonesPlayed"
  | "roundAttackHits"
  | "previousAttackBlocked"
  | "blockFacts"
  | "speedGainWindows"
  | "purchaseFacts"
  | "playedCardFacts"
  | "attackFacts"
>;

export type ComboHostCardLookup = (cardId: string) => ComboRuntimeCard | null | undefined;

export function emptyComboHostFacts(): ComboHostFacts {
  return {
    startingHandIds: [],
    turnPlayed: [],
    roundPlayed: [],
    sinceLastTurnPlayed: [],
    turnAttacks: [],
    roundAttacks: [],
    sinceLastTurnAttacks: [],
    roundBlocks: [],
    sinceLastTurnBlocks: [],
    speedGainedSinceLastTurn: false,
    purchasesSinceLastAscend: [],
    previousAttackBlocked: false,
  };
}

export function beginComboHostTurn(facts: ComboHostFacts, handIds: readonly string[]): ComboHostFacts {
  return {
    ...facts,
    startingHandIds: [...handIds],
    turnPlayed: [],
    turnAttacks: [],
    previousAttackBlocked: false,
  };
}

/**
 * Hide closes the "since my last turn" window. Facts generated by the opposing
 * turn are recorded after this reset and remain available when this fighter's
 * next turn begins.
 */
export function closeComboHostTurn(facts: ComboHostFacts): ComboHostFacts {
  return {
    ...facts,
    sinceLastTurnPlayed: [],
    sinceLastTurnAttacks: [],
    sinceLastTurnBlocks: [],
    speedGainedSinceLastTurn: false,
  };
}

export function beginComboHostRound(facts: ComboHostFacts): ComboHostFacts {
  return {
    ...facts,
    roundPlayed: [],
    roundAttacks: [],
    roundBlocks: [],
  };
}

/** Begin Ascend before purchases are made so new purchases survive until next Ascend. */
export function beginComboHostAscend(facts: ComboHostFacts): ComboHostFacts {
  return { ...facts, purchasesSinceLastAscend: [] };
}

export function recordComboHostCardPlayed(facts: ComboHostFacts, cardId: string, zone?: string): ComboHostFacts {
  const fact = { cardId, ...(zone ? { zone } : {}) };
  return {
    ...facts,
    turnPlayed: [...facts.turnPlayed, fact],
    roundPlayed: [...facts.roundPlayed, fact],
    sinceLastTurnPlayed: [...facts.sinceLastTurnPlayed, fact],
  };
}

export function recordComboHostAttack(
  facts: ComboHostFacts,
  cardId: string,
  zone: string,
  result: { hit: boolean; reversal?: boolean; blocked?: boolean },
): ComboHostFacts {
  const fact: ComboHostAttackFact = {
    cardId,
    zone,
    hit: Boolean(result.hit),
    reversal: Boolean(result.reversal),
    blocked: Boolean(result.blocked),
  };
  return {
    ...facts,
    turnAttacks: [...facts.turnAttacks, fact],
    roundAttacks: [...facts.roundAttacks, fact],
    sinceLastTurnAttacks: [...facts.sinceLastTurnAttacks, fact],
    previousAttackBlocked: fact.blocked,
  };
}

export function recordComboHostBlock(
  facts: ComboHostFacts,
  defenseCardId: string | undefined,
  incomingZone: string | undefined,
  equipmentCount?: number,
): ComboHostFacts {
  const fact: ComboHostBlockFact = { defenseCardId, incomingZone, equipmentCount };
  return {
    ...facts,
    roundBlocks: [...facts.roundBlocks, fact],
    sinceLastTurnBlocks: [...facts.sinceLastTurnBlocks, fact],
  };
}

export function recordComboHostSpeedGain(facts: ComboHostFacts): ComboHostFacts {
  return { ...facts, speedGainedSinceLastTurn: true };
}

export function recordComboHostPurchase(facts: ComboHostFacts, cardId: string): ComboHostFacts {
  return { ...facts, purchasesSinceLastAscend: [...facts.purchasesSinceLastAscend, { cardId }] };
}

function cardFor(lookup: ComboHostCardLookup, cardId: string) {
  return lookup(cardId) ?? null;
}

function playedFacts(source: readonly ComboHostPlayedFact[], window: ComboPlayedCardFact["window"], lookup: ComboHostCardLookup): ComboPlayedCardFact[] {
  return source.flatMap((fact) => {
    const card = cardFor(lookup, fact.cardId);
    return card ? [{ window, card, zone: fact.zone }] : [];
  });
}

function attackFacts(source: readonly ComboHostAttackFact[], window: ComboAttackFact["window"], lookup: ComboHostCardLookup): ComboAttackFact[] {
  return source.flatMap((fact) => {
    const card = cardFor(lookup, fact.cardId);
    return card ? [{ window, card, zone: fact.zone, hit: fact.hit, reversal: fact.reversal, blocked: fact.blocked }] : [];
  });
}

function blockFacts(source: readonly ComboHostBlockFact[], window: ComboBlockFact["window"], lookup: ComboHostCardLookup): ComboBlockFact[] {
  return source.map((fact) => {
    const defense = fact.defenseCardId ? cardFor(lookup, fact.defenseCardId) : null;
    return {
      window,
      defenseTags: defense?.tags ?? [],
      incomingZone: fact.incomingZone,
      equipmentCount: fact.equipmentCount,
    };
  });
}

function purchaseFacts(source: readonly ComboHostPurchaseFact[], lookup: ComboHostCardLookup): ComboPurchaseFact[] {
  return source.flatMap((fact) => {
    const card = cardFor(lookup, fact.cardId);
    if (!card) return [];
    return [{ window: "sinceLastAscend", tags: card.tags ?? [], family: card.subtype ?? card.cardType ?? "" }];
  });
}

/**
 * Converts generic host history into the canonical Combo runtime fact language.
 * No Combo IDs or printed requirement prose are interpreted here.
 */
export function comboRuntimeContextFromHostFacts(
  facts: ComboHostFacts,
  base: ComboHostBaseContext,
  lookup: ComboHostCardLookup,
): ComboRuntimeContext {
  const startingHand = facts.startingHandIds.map((id) => cardFor(lookup, id)).filter((card): card is ComboRuntimeCard => Boolean(card));
  const roundZonesPlayed = facts.roundAttacks.map((fact) => fact.zone).filter((zone): zone is string => Boolean(zone));
  const roundAttackHits = facts.roundAttacks.filter((fact) => fact.hit).length;
  return {
    ...base,
    startingHand,
    roundZonesPlayed,
    roundAttackHits,
    previousAttackBlocked: facts.previousAttackBlocked,
    playedCardFacts: [
      ...playedFacts(facts.turnPlayed, "turn", lookup),
      ...playedFacts(facts.roundPlayed, "round", lookup),
      ...playedFacts(facts.sinceLastTurnPlayed, "sinceLastTurn", lookup),
    ],
    attackFacts: [
      ...attackFacts(facts.turnAttacks, "turn", lookup),
      ...attackFacts(facts.roundAttacks, "round", lookup),
      ...attackFacts(facts.sinceLastTurnAttacks, "sinceLastTurn", lookup),
    ],
    blockFacts: [
      ...blockFacts(facts.roundBlocks, "round", lookup),
      ...blockFacts(facts.sinceLastTurnBlocks, "sinceLastTurn", lookup),
    ],
    speedGainWindows: facts.speedGainedSinceLastTurn ? ["sinceLastTurn"] : [],
    purchaseFacts: purchaseFacts(facts.purchasesSinceLastAscend, lookup),
  };
}
